apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - configmap.yaml
  - rbac.yaml
  - deployments/backend-deployment.yaml
  - deployments/frontend-deployment.yaml
  - services/backend-service.yaml
  - services/frontend-service.yaml
  - ingress.yaml

commonLabels:
  managed-by: developer-self-service
  app.kubernetes.io/name: developer-self-service
  app.kubernetes.io/part-of: developer-portal

